
* Orientation                                                      :noexport:
* Introduction
* Data Processing
** End Result
Dataframe so that each row uniquely defines a county at a given time, and includes
- Number of shootings (totally collapsed)
- Population of county
- Covariates
  - Gini coefficient
* Modeling
** Poisson
This approach came out of a meeting with Kerby Shedden on [2017-08-04 Fri].

Let's make this super simple and assume that we have just one county and aren't concerned with race.

X is observed shootings in a time period, so X ~ Poisson(\lambda)
We could say that \lambda~N(\mu,\sigma)

Let's introduce the notion of repeated measures, so now

X = (X_{1},X_{2})

now, X_{i} ~ Poisson(\lambda_{i})

\lambda_{i} ~ MvNorm(\Mu,\Sigma)

We're interested in inference on \Sigma, particularly the off-diagonal elements, as these tell us about the consistency of the risk.

Now let's consider that different counties will have different populations.

We define the interval space to be people, so \lambda is actually the shooting rate per capita.

Now, X_i ~ N_{i}*Poisson(\lambda_i)

let 
- X_{i,j} be the number of observed shootings at timeperiod i for county j
- N_i,j be the number of people (in convenient units) at timeperiod i for county j

X_{i,j} ~ N_{i,j} * Poisson(\lambda_i,j) 

and \lambda_{i,j} ~ MNormal(\Mu_{j},\Sigma)

\Mu_j = linear model based on covariates for that county at time i

\Sigma ~ some prior? I dunno


Kerby's notation looks like Poisson regression

E(Y|x) = e^{\theta'x} yeah definitely

#+BEGIN_SRC R :session 
  poismodel <- '

#+END_SRC
